Repository RimlTempest/StampApp, pull requests merged in 2021-07, with the labels that each got.

#100 update:スタンプの画像をstampNumから取得し、それをスタンプ一覧、スタンプ詳細に表示する
  lib/View/home.dart
  lib/Widget/stampDialog.dart
Labels: 修正💦

#108 add: CIの追加
  .github/workflows/flutter.yml
Labels: 新機能💡

#109 delete: 必要のないテストの削除
  test/widget_test.dart
Labels: high, 修正💦

#110 罫線の太さ変更
  lib/View/terms.dart
Labels: デザイン, フィードバック🎤

#114 1部テストがActionsで動いていないので動くように修正
  lib/Util/checkIsMaxStamps.dart
  lib/Util/toInt.dart
  lib/View/home.dart
  test/checkIsMaxStamps_test.dart
  test/hexColor_test.dart
  test/qrScan_test.dart
  test/toDateOrTime_test.dart
  test/toInt_test.dart
Labels: high, バグ🐛, 修正💦

#111 update：設定画面の項目のアイコンの変更
  lib/View/Setting.dart
Labels: デザイン

#112 fix:説明画面にて特定サイズにてデザインが崩れていため修正
  lib/View/instructions.dart
Labels: バグ🐛, 修正💦

#120 利用履歴ページのアイコンを分かりやすいものに変更
  assets/images/other/StampIcon.ttf
  lib/View/history.dart
  lib/Widget/stamp_icon_icons.dart
  pubspec.yaml
Labels: デザイン

#122 一部ダークモードにならない箇所の修正
  lib/View/Setting.dart
  lib/View/history.dart
  lib/View/instructions.dart
Labels: リファクタリング🔨

#123 update:QRのpathのバリデーション追加
  lib/Util/validation.dart
  lib/Widget/qrScan.dart
  test/qrScan_test.dart
Labels: high, 修正💦

#121 update:プライバシーポリシー等の最下層に空白部分を追加
  lib/View/home.dart
  lib/View/privacyPolicy.dart
  lib/View/terms.dart
Labels: デザイン, フィードバック🎤, 修正💦

#125 "update：画像の追加
  assets/images/stamp/stamp1.png
  assets/images/stamp/stamp2.png
  assets/images/stamp/stamp3.png
  assets/images/stamp/stamp5.png
  assets/images/stamp/stamp6.png
Labels: 新機能💡

#99 スタンプ画面のデザイン進捗報告
  .github/workflows/flutter.yml
  assets/images/other/logo_Contrast.png
  document/iOS_Build.md
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  lib/Constants/version.dart
  lib/Util/enumCheckString.dart
  lib/Util/enumDateType.dart
  lib/Util/toDateOrTime.dart
  lib/Util/toInt.dart
  lib/Util/validation.dart
  lib/View/Setting.dart
  lib/View/history.dart
  lib/View/home.dart
  lib/View/instructions.dart
  lib/View/qrSample.dart
  lib/View/sample.dart
  lib/Widget/qrAlertDialog.dart
  lib/Widget/qrScan.dart
  lib/Widget/stampDialog.dart
  lib/dbInterface.dart
  lib/main.dart
  lib/models/memo.dart
  lib/models/stamp.dart
  test/qrScan_test.dart
  test/stampTest.dart
  test/widget_test.dart
Labels: デザイン

#126 Home画面のデザイン作成
  lib/View/home.dart
  pubspec.yaml
Labels: デザイン

#133 DBInterfaceのテスト追加
  pubspec.yaml
  test/dbInterface_test.dart
Labels: high, 新機能💡

#132 ロゴを表示するように修正
  lib/View/home.dart
Labels: high, バグ🐛

#106 スタンプ使用処理追加
  lib/Util/enumStampCount.dart
  lib/View/Setting.dart
  lib/dbInterface.dart
Labels: high, 修正💦, 質問❓

#136 hotfix: マージで余計なところが残っちゃったぽいので緊急修正
  lib/View/Setting.dart
Labels: high, バグ🐛, 修正💦

#135 fix: QRのpathデータから画像を読み込むように修正
  lib/View/home.dart
Labels: high, バグ🐛, 修正💦

#138 リファクタリング
  lib/View/home.dart
  lib/Widget/stamp_icon_icons.dart
  lib/main.dart
  test/dbInterface_test.dart
Labels: リファクタリング🔨

#141 空白の大きさを調整
  lib/View/privacyPolicy.dart
Labels: デザイン, フィードバック🎤, 修正💦

#143 空スタンプ内の数字が正しく表示されないバグの修正
  lib/View/home.dart
Labels: バグ🐛, フィードバック🎤

#129 使い方画面の画像を新しいものに差し替え
  assets/images/instructions/history.jpg
  assets/images/instructions/history.png
  assets/images/instructions/home.jpg
  assets/images/instructions/home.png
  assets/images/instructions/setting.jpg
  assets/images/instructions/setting.png
  lib/View/instructions.dart
Labels: デザイン

#145 ホーム画面の合計スタンプ数を正しく表示されるようにする
  lib/View/home.dart
Labels: バグ🐛, 修正💦

#144 fix:スタンプリストにデータが残るのを修正
  lib/Util/toInt.dart
  lib/View/home.dart
  lib/dbInterface.dart
  lib/main.dart
  test/toInt_test.dart
Labels: high, バグ🐛, 修正💦

#148 fix:設定画面のヘッダーだけ色が違うバグを修正
  lib/View/Setting.dart
Labels: 修正💦

#151 定数の一元管理化
  lib/Constants/setting.dart
  lib/Constants/version.dart
  lib/View/Setting.dart
  lib/View/history.dart
  lib/View/home.dart
  lib/View/instructions.dart
  lib/View/privacyPolicy.dart
  lib/View/terms.dart
  test/qrScan_test.dart
Labels: 修正💦

#155 fix:スタンプ使用のダイアログのOKcancelボタンのデザインを統一
  lib/View/Setting.dart
Labels: デザイン, 修正💦

#153 fix: ダークモード対応
  lib/View/Setting.dart
  lib/View/history.dart
Labels: 修正💦

#157 スタンプ合計数の文字を中央揃えに修正
  lib/View/home.dart
Labels: デザイン, 修正💦

#163 利用履歴が狂う問題を修正
  lib/Constants/setting.dart
  lib/Util/Enums/enumCheckString.dart
  lib/Util/Enums/enumDateType.dart
  lib/Util/Enums/enumStampCount.dart
  lib/Util/toDateOrTime.dart
  lib/Util/validation.dart
  lib/View/Setting.dart
  lib/View/history.dart
  lib/View/home.dart
  lib/dbHelper.dart
  lib/dbInterface.dart
  lib/models/stamp.dart
  lib/models/stampLogs.dart
  test/qrScan_test.dart
  test/toDateOrTime_test.dart
Labels: high, バグ🐛, 修正💦

#166 スタンプを交換する際の個数を明示
  lib/View/Setting.dart
Labels: 修正💦

#167 スタンプテーブルのカラム修正
  lib/View/Setting.dart
  lib/View/home.dart
  lib/dbHelper.dart
  lib/dbInterface.dart
  lib/models/stamp.dart
Labels: 修正💦

#179 imageという文字を消す
  lib/Widget/stampDialog.dart
Labels: デザイン, 修正💦

#178 Fix/i18n/r
  l10n.yaml
  lib/View/Setting.dart
  lib/View/history.dart
  lib/View/home.dart
  lib/Widget/qrAlertDialog.dart
  lib/Widget/qrScan.dart
  lib/Widget/stampMaxDialog.dart
  lib/l10n/app_en.arb
  lib/l10n/app_ja.arb
  lib/main.dart
  pubspec.yaml
Labels: 新機能💡

#181 ホーム画面のデザインを更新
  lib/View/home.dart
  pubspec.yaml
Labels: デザイン, 修正💦

#184 画面を縦固定に
  lib/main.dart
Labels: 新機能💡

#182 Fix/stamp dialog/171 設定画面のスタンプ使用をリストではなくボタンにする
  lib/View/Setting.dart
Labels: デザイン

#185 使い方画面の画像を画像と説明文に分離
  assets/images/instructions/history.jpg
  assets/images/instructions/home.jpg
  assets/images/instructions/setting.jpg
  lib/View/instructions.dart
  lib/l10n/app_en.arb
  lib/l10n/app_ja.arb
Labels: 修正💦

#176 QRScanのライブラリの移行
  android/app/build.gradle
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  lib/Util/Enums/enumCheckString.dart
  lib/Util/Enums/enumStampCount.dart
  lib/Util/toDateOrTime.dart
  lib/Util/validation.dart
  lib/View/Setting.dart
  lib/View/history.dart
  lib/View/home.dart
  lib/View/instructions.dart
  lib/View/privacyPolicy.dart
  lib/View/qrScan.dart
  lib/View/terms.dart
  lib/Widget/CameraButton.dart
  lib/Widget/SettingButton.dart
  lib/Widget/qrAlertDialog.dart
  lib/Widget/qrDialog.dart
  lib/Widget/qrScan.dart
  lib/Widget/stampMaxDialog.dart
  lib/Widget/stamp_icon_icons.dart
  lib/dbInterface.dart
  lib/main.dart
  lib/models/stamp.dart
  lib/models/stampLogs.dart
  pubspec.lock
  pubspec.yaml
  test/dbInterface_test.dart
  test/qrScan_test.dart
Labels: high, 修正💦, 質問❓

#190 全体的なコードのリファクタリング＆修正
  lib/Constants/setting.dart
  lib/Util/Enums/enumCheckString.dart
  lib/Util/Enums/enumStampCount.dart
  lib/Util/toDateOrTime.dart
  lib/View/Setting.dart
  lib/View/history.dart
  lib/View/home.dart
  lib/View/qrScan.dart
  lib/Widget/qrDialog.dart
  lib/Widget/qrScan.dart
  lib/Widget/stampDialog.dart
  lib/Widget/stamp_icon_icons.dart
  lib/dbInterface.dart
  lib/main.dart
Labels: 修正💦

#195 fix:スタンプ利用後のスタンプシートが更新されない不具合を修正
  lib/View/home.dart
Labels: バグ🐛, フィードバック🎤, 修正💦

#194 add:利用規約、プライバシーポリシー、その他のi18n対応
  lib/View/Setting.dart
  lib/View/home.dart
  lib/View/privacyPolicy.dart
  lib/View/qrScan.dart
  lib/View/terms.dart
  lib/Widget/stampDialog.dart
  lib/l10n/app_en.arb
  lib/l10n/app_ja.arb
  lib/main.dart
Labels: 修正💦

#198 使い方画面の画像の差し替え
  assets/images/instructions/history.jpg
  assets/images/instructions/home.jpg
  assets/images/instructions/setting.jpg
Labels: デザイン, 修正💦

#203 fix:i18n対応抜け修正
  lib/View/Setting.dart
  lib/Widget/stampDialog.dart
  lib/l10n/app_en.arb
  lib/l10n/app_ja.arb
Labels: 修正💦

#196 clean: スタンプ情報の日付のカラーなどを修正
  lib/Widget/stampDialog.dart
Labels: 修正💦

#205 clean:qrScan.dartのリファクタリング
  lib/View/qrScan.dart
Labels: リファクタリング🔨

#188 AppBarのコンポーネント分離
  lib/View/Setting.dart
  lib/View/history.dart
  lib/View/home.dart
  lib/View/instructions.dart
  lib/View/privacyPolicy.dart
  lib/View/terms.dart
  lib/Widget/AppBar.dart
Labels: デザイン, 修正💦

#207 履歴削除ボタンを配置
  lib/View/history.dart
Labels: 新機能💡

#206 fix:ダイアログ、アラートのボタンの統一化
  lib/View/Setting.dart
  lib/Widget/stampDialog.dart
Labels: デザイン, 修正💦

#209 Linter導入
  analysis_options.yaml
  lib/View/instructions.dart
  lib/View/privacyPolicy.dart
  lib/View/terms.dart
  lib/Widget/CameraButton.dart
  lib/Widget/HexColor.dart
  lib/Widget/SettingButton.dart
  pubspec.lock
  pubspec.yaml
Labels: 新機能💡

#211 fix:履歴削除のi18n対応
  lib/View/history.dart
  lib/l10n/app_en.arb
  lib/l10n/app_ja.arb
Labels: 修正💦

#217 ダークモードのホーム画面で数字とスタンプ数が出るように修正
  lib/View/home.dart
Labels: デザイン, 修正💦

#220 スタンプダイアログでスタンプ情報読み込み時不正な値が入る問題解消
  lib/View/home.dart
Labels: バグ🐛, 修正💦

#218 スタンプ消費のさい使用したスタンプ履歴が全部でるのを一個で済むように
  lib/View/Setting.dart
Labels: 修正💦

#221 スタンプ使用した際にIDが表示されるのを日付にする
  lib/Util/toDateOrTime.dart
  lib/View/Setting.dart
  lib/Widget/stampDialog.dart
Labels: 修正💦

#212 スタンプ画面のサイズを端末サイズによって揃える
  lib/View/home.dart
Labels: デザイン, 修正💦

#223 fix:スタンプ履歴画面のマージンを調整する
  lib/View/history.dart
Labels: デザイン, 修正💦

#225 全体を通してリファクタリング
  assets/images/other/my4.png
  lib/View/Setting.dart
  lib/View/history.dart
  lib/View/home.dart
  lib/View/privacyPolicy.dart
  lib/View/qrScan.dart
  lib/Widget/AppBar.dart
  lib/Widget/stampDialog.dart
  lib/Widget/stampIcons.dart
  lib/dbInterface.dart
  lib/main.dart
  lib/models/stamp.dart
  lib/models/stampLogs.dart
Labels: リファクタリング🔨, 修正💦
