Repository RimlTempest/StampApp, pull requests merged in 2021-06, with the labels that each got.

#67 利用履歴の途中経過
  lib/View/Setting.dart
  lib/View/history.dart
  lib/main.dart
Labels: たすけて💧, デザイン

#65 add:スタンプテーブルの設計
  lib/Util/enumDateType.dart
  lib/Util/toDateOrTime.dart
  lib/Util/toInt.dart
  lib/View/home.dart
  lib/View/sample.dart
  lib/Widget/stampDialog.dart
  lib/dbInterface.dart
  lib/models/memo.dart
  lib/models/stamp.dart
  pubspec.yaml
  test/stampTest.dart
Labels: high, 新機能💡

#73 update:スタンプの表示変更と画像表示の途中経過
  assets/images/flower-4.png
  assets/images/my4.png
  assets/images/none.png
  lib/View/home.dart
  lib/Widget/stampDialog.dart
  lib/Widget/stampMaxDialog.dart
  lib/checkIsMaxStamps.dart
  pubspec.yaml
  test/checkIsMaxStampsTest.dart
Labels: high, 新機能💡

#74 add: バリデーション処理の追加
  lib/Widget/qrScan.dart
  pubspec.yaml
  test/qrScan_test.dart
Labels: 新機能💡, 質問❓

#81 fix:assets/imageと/imageの統合と階層分け
  assets/images/instructions/history.png
  assets/images/instructions/home.png
  assets/images/instructions/setting.png
  assets/images/other/logo_transparent.png
  assets/images/other/my4.png
  assets/images/stamp/flower-4.png
  assets/images/stamp/none.png
  lib/View/home.dart
  lib/View/instructions.dart
  pubspec.yaml
Labels: 修正💦

#76 fix:利用規約とプライバシーポリシーのヘッダー部分の色を修正
  lib/View/privacyPolicy.dart
  lib/View/terms.dart
  lib/Widget/HexColor.dart
  test/HexColorTest.dart
Labels: 修正💦

#83 fix:分離したhexColorをそれぞれの画面で適用
  lib/View/Setting.dart
  lib/View/history.dart
  lib/View/home.dart
  lib/View/instructions.dart
Labels: 修正💦

#85 update： タイトルを画像に差し替え
  assets/images/other/logo_Contrast.png
  lib/View/home.dart
Labels: good first issue, デザイン

#84 update: 設計したモデルを元にスタンプ履歴画面の機能を実装
  lib/Util/toDateOrTime.dart
  lib/View/history.dart
  lib/dbInterface.dart
  lib/models/stamp.dart
Labels: high, 修正💦

#87 update:モデルに基づきスタンプ機能の実装途中
  lib/Util/enumCheckString.dart
  lib/View/home.dart
  lib/Widget/qrAlertDialog.dart
  lib/Widget/qrScan.dart
  lib/Widget/stampDialog.dart
  lib/dbInterface.dart
Labels: high, 新機能💡

#92 remove:不要なコンポーネントの削除
  lib/View/home.dart
  lib/View/qrSample.dart
  lib/View/sample.dart
  lib/main.dart
  lib/models/memo.dart
Labels: 修正💦

#95 update:qrScanのバリデーションの分離
  lib/Util/validation.dart
  lib/Widget/qrScan.dart
  test/qrScan_test.dart
Labels: 修正💦

#94 リファクタリング
  lib/Util/enumCheckString.dart
  lib/Util/enumDateType.dart
  lib/Util/toDateOrTime.dart
  lib/Util/toInt.dart
  lib/View/history.dart
  lib/View/home.dart
  lib/models/stamp.dart
  test/stampTest.dart
Labels: リファクタリング🔨, 修正💦

#98 fix: バージョンを上げた
  lib/Constants/version.dart
  lib/View/Setting.dart
Labels: high, 修正💦

#105 iOSデバック周りのエラー解消
  document/iOS_Build.md
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Labels: 修正💦
